# USEI CHATGPT PARA PESQUISA(não pensei na fórmula de divisão)
m = float(input("Uma distância em metros: "))
print (f"A medida de {m}m corresponde a")
print (f"{m / 1000:.3f} km")
print (f"{m / 100:.2f} hm")
print (f"{m / 10:.1f} dam")
print (f"{m * 10} dm")
print (f"{m * 100} cm")
print (f"{m * 1000} mm")